id: A999DA9E1
title: 'Highway of the Great Yoga: A Daily Practice for the Peaceful and Wrathful
  Deities of the Self-Liberated Wisdom Mind'
type: translation
pechas:
- I13C44D74
- I368EA039
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:44:30.498168
  last_modified_at: 2023-01-04 11:44:30.498173
  collections:
  - Dodrupchen Jigme Trinle Özer Series
  - Works of Tibetan Masters
alignment_to_base:
  I13C44D74/B786: 417E
  I368EA039/823D: 417E
